### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ka194#1]
[infografia de la liberia.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ka194/files/11084589/infografia.de.la.liberia.pdf)

**Comment by Arlet04** [comment]
Partes de infografía: Faltaron las referencias bibliográficas 3 
Coherencia:excelente 4 
Organización: Excelente 4 
Diseño: excelente 4 
Creatividad:excelente 4
Puntos : 19/20
Calificación: 19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
